import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'



export default function Home() {
  return (
    <div className='bg-gray-50 min-h-screen'>
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   {/* header  */}
 
 <Header/>

   {/* feed  */}
<Feed/>

   {/* footer  */}


    
    </div>
  )
}
